# Generated by Django 4.1.13 on 2023-11-16 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='date',
        ),
        migrations.AddField(
            model_name='movie',
            name='actor',
            field=models.CharField(default='', max_length=100),
        ),
    ]
