# Generated by Django 4.1.13 on 2023-11-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_remove_movie_date_movie_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.CharField(default='', max_length=100),
        ),
    ]
